name: Lint Python Code

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Request Details
        run: echo "Pull request with title '${{ github.event.pull_request.title }}' has been created."
  
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint code
        run: flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
        working-directory: ${{ github.workspace }}
